[package]
name = "rpc"
version = "0.1.1"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
bytes = "0.4"
chrono = "0.4"
dotenv = "0.13"
futures = "0.1"
#hyper = "0.12"
#r2d2 = "0.8"
#r2d2_postgres = "0.14"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-signal = "0.2"

[dependencies.reqwest]
version = "0.9"
features = ["socks"]

[dependencies.rpdb]
version = "0.1.1"
git = "https://github.com/serbe/rpdb"