[package]
name = "rpc"
version = "0.2.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
crossbeam = "0.7"
dotenv = "0.14"
futures = "0.1"
hyper = "0.12"
postgres = { version = "0.15", features = ["with-chrono"] }
reqwest = { version = "0.9", features = ["socks"] }
sled = "0.26"
