[package]
name = "rpc"
version = "0.2.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
bytes = "0.4"
chrono = "0.4"
dotenv = "0.14"
futures = "0.1"
sled = "0.24"

[dependencies.reqwest]
version = "0.9"
features = ["socks"]

[dependencies.postgres]
version = "0.15"
features = ["with-chrono"]
