[package]
name = "rpc"
version = "0.1.1"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
crossbeam-channel = "0.3"
dotenv = "0.13"
futures = "0.1"
hyper = "0.12"
tokio = "0.1"
tokio-threadpool = "0.1"

[dependencies.reqwest]
version = "0.9"
features = ["socks"]

[dependencies.rpdb]
version = "0.1.1"
git = "https://github.com/serbe/rpdb"